kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: false
  kubeProxyMode: "nftables"
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 10249
        hostPort: 10249
  - role: worker
  - role: worker